# mise.toml
[tools]
neovim = "latest"
node = "24.10.0"
pnpm = "latest"
ripgrep = "latest"
btop = "latest"
fd = "latest"
docker-cli = "latest"
just = "latest"
go = "1.25.3"
python = "latest"
rust = "latest"
opentofu = "latest"
television = "latest"
gemini-cli = "latest"
claude = "latest"
k9s = "latest"
kubectl = "latest"
"ubi:sst/opencode" = "latest"
starship = "latest"
atuin = "latest"
lazygit = "latest"
lazydocker = "latest"
gh = "latest"
